### PR TITLE
Datasets API

### PR DESCRIPTION
**Pull request by karissa**

### CODE REVIEW

**Comment by noffle** [comment]
What is settings used for?

**Comment by karissa** [comment]
I guess it's not necessary for now. But the idea is to give clients the ability to implement UIs that change the datasetRoot in the case you want to store your datasets in special place for the device (or change USB?). Another feature I saw on the roadmap is changing the sync direction (pull, push, sync) which is upcoming.

**Comment by gmaclennan** [comment]
@karissa I think we want to keep this REST (stateless), so I think we should avoid settings like this because it will make things harder down the way I think.

I realize that we haven't really thought through different presets and different datasets on mobile and how to handle these, and there are currently some differences with implementation between mobile and desktop.

I think where we want to get to, at least mid-term (pending implementation of some kind of "group" functionality to keep data separated within a single database) is to have everything namespaced under datasets on the server, including presets. This would mean having presets and datasets tied together, which I think is fine, since mixing presets with the same dataset would lead to confusing things happening right now.

Therefore I think endpoints should be like:

- `/datasets` (list all datasets on device)
- `/datasets/:datasetId/presets` (list of all presets)
- `/datasets/:datasetId/observations` (list of all observations)
- `/datasets/:datasetId/media` (all the media endpoints)
- `/datasets/:datasetId/sync` (sync scan/advertise only showing matching datasets).

I think for now we can keep `/styles` device specific rather than dataset specific, although we might want to change this in the future.

When do we need to change the routes? Can we start to support some kind of dataset checks without needing these routes? I think so.

What we should implement sooner I think is advertising datasetID in the sync announce.

Where do we read the datasetID from? Currently we have no phone UI for changing presets, and I don't think we need one. Currently the presets that the phone shows are the ones that are first in the presets folder (lexographic sort). This is fine for current uses. Perhaps we can read the datasetId from that preset file on the server?

For sync, I think the server should ideally do both USB and wifi discovery. USB discovery: check for connected removable drives, check if they have a file `MapeoData.mapeosync` in their root, check the datasetId in the userData of the sync file, include it in the list of targets.

I still need to do some more testing of USB drive detection on mobile. It seems like USB OTG drives are always mounted in the same folder `/storage` under a unique ID. There is a Java API for this, with one React-native implementation that I have found https://github.com/scizers/react-native-otg-storage but it would be best if we can do this all in the server process, just checking the `/storage` folder.

The alternative is that we do USB sync drive discovery on the react-native process, then pass the filename to mapeo-server in the sync request.

I don't think the location of the USB syncfile should be in serverOpts as `datasetRoot` since USB drives mount in different locations, and the user will connect and disconnect USB drives during the life of the server process.

**Comment by karissa** [comment]
I would be hesitant to put any USB scanning into `mapeo-server`. Since devices can be very different on different platforms (mobile vs desktop vs raspberry pi). Since mapeo-server is a developer tool called by another node process, I think we can safely offload that to userland. Mapeo Server should just care about where the 'root' is on the filesystem, where it should store datasets.

On mobile, we can then implement USB drive scanning from either react-native or rnnode, whichever seems to be more stable and easier to manage. Desktop will have an entirely different way of implementing this also. For mobile, there can be an extra route created which is returns the valid USB drives.

Also, I'm not sure why REST needs to be stateless in your view -- REST is usually on top of a database (perhaps settings could be persisted on disk). You're probably right though that we don't need settings right now...

**Comment by karissa** [comment]
Imaging a route like:
```
/datasets/list
```
Which could return 
* `[]`: no datasets found
* `{error: 'usb-unpluggged'}`
* `[<Dataset>, <Dataset>]`

Dataset object could simply be all the stuff in the `userdata` fields on the syncfile along with the filepath. If you want to sync, you can then hit `/sync/start/?filepath=${dataset.filepath}`

**Comment by noffle** [comment]
I don't have a strong feeling either way re whether USB scanning is in mapeo-server or in the app.

**Comment by noffle** [comment]
Having it in mapeo-server would be convenient (nice, single fully-featured package), but it also means probably relying on some native modules, which I'm not sure (yet) how we'd manage to selectively build by platform.

**Comment by noffle** [comment]
But maybe that's a solved problem & isn't that hard to deal with! I think if we can build it in and making it work by platform with minimal configuration isn't hard, we do it in mapeo-server. if not, in the app might be easier to manage.

**Comment by gmaclennan** [comment]
@karissa re. the stateless stuff, what I mean is that changing the settings changes what is returned by the other routes, so they depend on the server state. If the server restarts you would need to POST to `/settings` to get the same back from the other routes, if I'm understanding right.

However, I'm not quite understanding the dataset stuff, so perhaps we're thinking different things. I was imagining datasets being something that exist on the device, not on a USB drive. A device currently only supports having one dataset, but we would want to add a UI for having more in the future. `/datasets` would return the ids of the datasets on the device.

As for USB discovery, it is different on mobile and desktop, but it's quite low-level stuff so it would be nice if core/server could handle this. I'm not sure if it can anyway on mobile though, so it might need to be in client (react-native) code.

I think if we do discovery on the server it should be in the sync API `/sync/devices` which would also include a field to indicate usb or wifi.

**Comment by noffle** [comment]
@gmaclennan are you imagining that each current route (or most) would be prefixed with the dataset id? So, someone might create e.g. a new observation with
```
PUT /datasets/waorani/observation
```?

If so, then we could also do sync similarly, like `GET /datasets/waorani/sync` to get sync targets for the `waorani` dataset id.

**Comment by gmaclennan** [comment]
@noffle yes that is what I am imagining. At least until we have a capability system which would allow different access rights within a single DB which is selectively synced.

**Pull request closed without merging**
